version: 0.2

phases:
  install:
    commands:
      # Navigate to your application's directory
      - echo "Starting build..."
      
artifacts:
  files:
    # Package ALL files from the current location (which is now my-beanstalk-app)
    - '**/*'

